name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -o helloworld

    - name: Upload artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: helloworld
        path: ./helloworld
        
  run:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2.0.10
        with:
          name: helloworld
      
      - name: Run
        run: ./helloworld
